
SET SERVEROUTPUT ON;

/*Création de la table REGION */

CREATE TABLE SYSTEM.REGION(
    CODE_REGION NUMBER PRIMARY KEY,
    LIBELLE_REGION VARCHAR2(100) NOT NULL);


/*Création de la table FAMILLE */
    
CREATE TABLE SYSTEM.FAMILLE(
    CODE_FAMILLE NUMBER PRIMARY KEY,
    LIBELLE_FAMILLE VARCHAR2(100) NOT NULL);

/*Création de la table CATEGORIE*/

CREATE TABLE SYSTEM.CATEGORIE(
    CODE_CATEGORIE NUMBER PRIMARY KEY,
    LIBELLE_CATEGORIE VARCHAR2(100) NOT NULL);

/*Création de la table CLIENT */

CREATE TABLE SYSTEM.CLIENT(
    CODE_CLIENT NUMBER PRIMARY KEY,
    NOM VARCHAR2(30) NOT NULL,
    ADRESSE_VILLE VARCHAR2(100) NOT NULL,
    DATE_CONTACT DATE NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    CODE_REGION NUMBER, 
    FOREIGN KEY (CODE_REGION) REFERENCES SYSTEM.REGION(CODE_REGION));

    
/*Création de la table COMMANDE */

CREATE TABLE SYSTEM.COMMANDE(
    CODE_COMMANDE VARCHAR2(20) PRIMARY KEY,
    MONTANT_HT NUMBER ,
    MONTANT_TTC NUMBER ,
    DATE_COMMANDE DATE NOT NULL,
    CODE_CLIENT NUMBER,
    REGLAGE NUMBER,
    FOREIGN KEY (CODE_CLIENT) REFERENCES SYSTEM.CLIENT(CODE_CLIENT));


/*Création de la table PRODUIT */

CREATE TABLE SYSTEM.PRODUIT(
    REF_PRODUIT VARCHAR2(20) PRIMARY KEY,
    LIBELLE_PRODUIT VARCHAR2(200) NOT NULL,
    PU NUMBER NOT NULL,
    TVA VARCHAR2(20) NOT NULL,
    CODE_FAMILLE NUMBER,
    CODE_CATEGORIE NUMBER,
    FOREIGN KEY (CODE_FAMILLE) REFERENCES SYSTEM.FAMILLE(CODE_FAMILLE),
    FOREIGN KEY (CODE_CATEGORIE) REFERENCES SYSTEM.CATEGORIE(CODE_CATEGORIE));

/*Création de la table CMD_CONTENIR */
    
CREATE TABLE SYSTEM.CMD_CONTENIR(
    CODE_COMMANDE VARCHAR2(20),
    REF_PRODUIT VARCHAR2(20),
    QTE_COMMANDE NUMBER NOT NULL,
    FOREIGN KEY (CODE_COMMANDE) REFERENCES SYSTEM.COMMANDE(CODE_COMMANDE),
    FOREIGN KEY (REF_PRODUIT) REFERENCES SYSTEM.PRODUIT(REF_PRODUIT));