SET SERVEROUTPUT ON;
/*Table CATEGORIE: */

INSERT INTO SYSTEM.CATEGORIE VALUES(1,'RAM');
INSERT INTO SYSTEM.CATEGORIE VALUES(2,'DISQUE DUR EXTERNE');
INSERT INTO SYSTEM.CATEGORIE VALUES(3,'DISQUE DUR INTERNE');
INSERT INTO SYSTEM.CATEGORIE VALUES(4,'CARTE SON');
INSERT INTO SYSTEM.CATEGORIE VALUES(5,'CARTE GRAPHIQUE');

/*/Table CLIENT: */

INSERT INTO SYSTEM.CLIENT VALUES(1,'BENTAJER','Mhannech II, Tetouan','02/11/2019','ahmed@mail.com');
INSERT INTO SYSTEM.CLIENT VALUES(2,'ESSEGHIRI','Res Naoufal app 8, Maarif, Casablanca','27/10/2018','youssef@mail.com');
INSERT INTO SYSTEM.CLIENT VALUES(3,'Houty','Settat','20/11/2018','karim@mail.com');


/*Table COMMANDE: */

INSERT INTO SYSTEM.COMMANDE VALUES(866,4329,5036.4,'01/02/2019',2,1);
INSERT INTO SYSTEM.COMMANDE VALUES(123,21297,30011.16,'04/02/2019',1,1);
INSERT INTO SYSTEM.COMMANDE VALUES(412,1980,2217.6,'05/06/2018',3,1);
INSERT INTO SYSTEM.COMMANDE VALUES(234,3849,4498.8,'12/04/2018',2,1);


/*Table CMD_CONTENIR: */

INSERT INTO SYSTEM.CMD_CONTENIR VALUES(866,'A01',10);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(866,'A02',2);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(866,'B15',1);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(123,'A01',20);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(123,'B15',5);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(123,'C80',12);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(412,'A01',10);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(412,'A02',2);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(234,'A01',10);
INSERT INTO SYSTEM.CMD_CONTENIR VALUES(234,'B15',1);

/*Table FAMILLE: */

INSERT INTO SYSTEM.FAMILLE VALUES(1,'MEMOIRE');
INSERT INTO SYSTEM.FAMILLE VALUES(2,'CARTE');
INSERT INTO SYSTEM.FAMILLE VALUES(3,'DISQUE');

/*Table PRODUIT: */

INSERT INTO SYSTEM.PRODUIT VALUES('A01','Barrette Memoire 2Go',150,12%,1,1);
INSERT INTO SYSTEM.PRODUIT VALUES('A02','Barrette Memoire 4Go',240,12%,1,1);
INSERT INTO SYSTEM.PRODUIT VALUES('B15','Carte Graphique,4Go',2349,20%,2,5);
INSERT INTO SYSTEM.PRODUIT VALUES('A11','Carte son Asus Xonar',750,12%,2,4);
INSERT INTO SYSTEM.PRODUIT VALUES('C80','Disque Externe 1000G',546,33%,3,2);

/*Table REGION: */

INSERT INTO SYSTEM.REGION VALUES(1,'Tanger-T�touan-Al Hoce�ma');
INSERT INTO SYSTEM.REGION VALUES(2,'R�gion de l Oriental');
INSERT INTO SYSTEM.REGION VALUES(3,'R�gion de F�s-Mekn�s');
INSERT INTO SYSTEM.REGION VALUES(4,'R�gion de Rabat-Sal�-K�nitra');
INSERT INTO SYSTEM.REGION VALUES(5,'R�gion de B�ni Mellal-Kh�nifra');
INSERT INTO SYSTEM.REGION VALUES(6,'R�gion de Casablanca-Settat');
INSERT INTO SYSTEM.REGION VALUES(7,'R�gion de Marrakech-Safi');